"""add password hash

Revision ID: 4ad3dcadcd54
Revises: bdf99b5f86eb
Create Date: 2026-06-22 17:14:40.910482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.db.base import Base

# revision identifiers, used by Alembic.
revision: str = '4ad3dcadcd54'
down_revision: Union[str, Sequence[str], None] = 'bdf99b5f86eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password_hash')
    # ### end Alembic commands ###
