"""add password hash

Revision ID: 6d613e995615
Revises: aae863ccca49
Create Date: 2026-06-23 10:08:51.240143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.db.base import Base

# revision identifiers, used by Alembic.
revision: str = '6d613e995615'
down_revision: Union[str, Sequence[str], None] = 'aae863ccca49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###
