"""add password hash

Revision ID: aae863ccca49
Revises: e88b9ef27f86
Create Date: 2026-06-23 10:07:30.170291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.db.base import Base

# revision identifiers, used by Alembic.
revision: str = 'aae863ccca49'
down_revision: Union[str, Sequence[str], None] = 'e88b9ef27f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
