"""add is_verified column

Revision ID: e88b9ef27f86
Revises: 4ad3dcadcd54
Create Date: 2026-06-23 10:00:12.673055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.db.base import Base

# revision identifiers, used by Alembic.
revision: str = 'e88b9ef27f86'
down_revision: Union[str, Sequence[str], None] = '4ad3dcadcd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('User', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('User', 'is_verified')
    # ### end Alembic commands ###
